version: "3"
services:
  db:
    image: db:latest
    restart: always
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - "../efs:/usr/csvs"
  node:
    image: node-dev:latest
    restart: always
    ports:
      - "3000:8080"
    environment:
      - dbUSERNAME=postgres
      - dbPASSWORD=password
      - dbHOST=db
      - dbPORT=5432
      - dbDATABASE=q_and_a
    volumes:
      - "/usr/src/app/node_modules"
      - "./server:/usr/src/app"
